const https = require('https');
const fs = require('fs');
const path = require('path');

const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

function logEvent(obj) {
  const eventsPath = path.join(__dirname, 'ledger', 'events.log');
  fs.appendFileSync(eventsPath, JSON.stringify(obj) + '\n', 'utf8');
}

function logModelCall(obj) {
  const modelCallsPath = path.join(__dirname, 'ledger', 'model_calls.log');
  fs.appendFileSync(modelCallsPath, JSON.stringify(obj) + '\n', 'utf8');
}

if (!GITHUB_OWNER || !GITHUB_REPO || !GITHUB_TOKEN) {
  console.error('Missing required environment variables');
  process.exit(1);
}

async function createPR() {
  const branchName = 'sentinelchain-security-patch-2025-12-12T05-12-56'; // Use the existing branch

  const prData = JSON.stringify({
    title: '🔒 Security: Command Injection Protection Patches',
    head: branchName,
    base: 'main',
    body: `## Security Patches Applied

This PR contains automated security patches generated by SentinelChain to protect against command injection vulnerabilities.

### Changes Made:
- **Input Sanitization**: Added comprehensive command validation
- **Whitelist Implementation**: Restricted allowed commands to safe operations
- **Sandbox Hardening**: Enhanced security measures in sandbox environment

### Files Modified:
- \`sandbox/app.js\` - Applied security patches

### Validation:
- All patches tested in isolated sandbox environment
- Command injection vectors blocked
- Maintains backward compatibility for safe operations

---
*Generated by SentinelChain - Automated Security Analysis Framework*`
  });

  const options = {
    hostname: 'api.github.com',
    path: `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`,
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(prData),
      'User-Agent': 'SentinelChain-GitHub-Agent'
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          const response = JSON.parse(data);
          if (res.statusCode >= 200 && res.statusCode < 300) {
            resolve(response);
          } else {
            reject(new Error(`GitHub API error: ${res.statusCode} - ${response.message || data}`));
          }
        } catch (e) {
          reject(e);
        }
      });
    });

    req.on('error', reject);
    req.write(prData);
    req.end();
  });
}

async function main() {
  try {
    console.log('Creating PR with new token...');
    const prResponse = await createPR();
    const prUrl = prResponse.html_url;

    logEvent({
      time: new Date().toISOString(),
      type: 'github_pr_created',
      branch: 'sentinelchain-security-patch-2025-12-12T05-12-56',
      pr_url: prUrl,
      pr_number: prResponse.number
    });

    logModelCall({
      timestamp: new Date().toISOString(),
      agent: 'create_pr_only',
      action: 'pr_created',
      pr_url: prUrl,
      success: true
    });

    console.log(`✅ GitHub PR created successfully!`);
    console.log(`🔗 PR URL: ${prUrl}`);

  } catch (error) {
    console.error('❌ PR creation failed:', error.message);

    logModelCall({
      timestamp: new Date().toISOString(),
      agent: 'create_pr_only',
      error: error.message,
      success: false
    });

    logEvent({
      time: new Date().toISOString(),
      type: 'github_pr_failed',
      error: error.message
    });
  }
}

main();
