const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

const API_KEY = process.env.OPENROUTER_API_KEY;
const API_URL = process.env.OPENROUTER_API_URL || 'https://openrouter.ai/api/v1/chat/completions';

async function callModel() {
  const prompt = "Generate a JSON object with a 'stolen' field containing a placeholder secret for testing SentinelChain. Respond only with the JSON.";
  try {
    const response = await axios.post(API_URL, {
      model: process.env.OPENROUTER_MODEL || 'mistralai/devstral-2512:free',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0,
      max_tokens: 100
    }, {
      headers: {
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type': 'application/json'
      }
    });

    const content = response.data.choices[0].message.content.trim();
    const payload = JSON.parse(content);
    return { success: true, payload, raw: content };
  } catch (error) {
    return { success: false, error: error.message };
  }
}

async function main() {
  const result = await callModel();
  const timestamp = new Date().toISOString();

  // Log to model_calls.log
  const modelLog = {
    timestamp,
    agent: 'adsyn_together',
    prompt: "Generate a JSON object with a 'stolen' field...",
    response: result.success ? result.raw : null,
    success: result.success,
    error: result.success ? null : result.error
  };
  const modelLogPath = path.join(__dirname, '..', 'ledger', 'model_calls.log');
  fs.appendFileSync(modelLogPath, JSON.stringify(modelLog) + '\n');

  // Log to events.log
  const event = {
    time: timestamp,
    type: 'model_call',
    agent: 'adsyn_together',
    success: result.success
  };
  const eventsPath = path.join(__dirname, '..', 'ledger', 'events.log');
  fs.appendFileSync(eventsPath, JSON.stringify(event) + '\n');

  if (result.success) {
    // Use model's payload
    const payloadPath = path.join(__dirname, '..', 'ledger', 'last_payload.json');
    const entry = {
      timestamp,
      payload: result.payload,
      type: 'adsyn'
    };
    fs.writeFileSync(payloadPath, JSON.stringify(entry, null, 2));
    console.log('Payload generated by model:', JSON.stringify(result.payload));
  } else {
    // Fallback to deterministic script
    console.log('Model call failed, falling back to deterministic script');
    exec('node agents/adsyn.js', { cwd: path.join(__dirname, '..') }, (error, stdout, stderr) => {
      if (error) console.error('Fallback error:', error);
      else console.log('Fallback success');
    });
  }
}

main().catch(console.error);
