const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

const API_KEY = process.env.OPENROUTER_API_KEY;
const API_URL = process.env.OPENROUTER_API_URL || 'https://openrouter.ai/api/v1/chat/completions';

async function callModel(code) {
  const prompt = `Here is vulnerable Node.js code:\n\n${code}\n\nGenerate a patched version that adds input sanitization to prevent command injection. Respond only with the complete patched code.`;
  try {
    const response = await axios.post(API_URL, {
      model: process.env.OPENROUTER_MODEL || 'mistralai/devstral-2512:free',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0,
      max_tokens: 1000
    }, {
      headers: {
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type': 'application/json'
      }
    });

    const patchedCode = response.data.choices[0].message.content.trim();
    return { success: true, patchedCode };
  } catch (error) {
    return { success: false, error: error.message };
  }
}

async function main() {
  const appPath = path.join(__dirname, '..', 'sandbox', 'app.js');
  const code = fs.readFileSync(appPath, 'utf8');

  const result = await callModel(code);
  const timestamp = new Date().toISOString();

  // Log to model_calls.log
  const modelLog = {
    timestamp,
    agent: 'autofix_together',
    prompt: `Patch code prompt...`,
    response: result.success ? result.patchedCode : null,
    success: result.success,
    error: result.success ? null : result.error
  };
  const modelLogPath = path.join(__dirname, '..', 'ledger', 'model_calls.log');
  fs.appendFileSync(modelLogPath, JSON.stringify(modelLog) + '\n');

  // Log to events.log
  const event = {
    time: timestamp,
    type: 'model_call',
    agent: 'autofix_together',
    success: result.success
  };
  const eventsPath = path.join(__dirname, '..', 'ledger', 'events.log');
  fs.appendFileSync(eventsPath, JSON.stringify(event) + '\n');

  if (result.success) {
    // Write patched code
    const patchedPath = path.join(__dirname, '..', 'sandbox', 'app.patched.js');
    fs.writeFileSync(patchedPath, result.patchedCode);
    console.log('Patched code generated by model and written to:', patchedPath);
  } else {
    // Fallback to deterministic script
    console.log('Model call failed, falling back to deterministic script');
    exec('node agents/autofix.js', { cwd: path.join(__dirname, '..') }, (error, stdout, stderr) => {
      if (error) console.error('Fallback error:', error);
      else console.log('Fallback success');
    });
  }
}

main().catch(console.error);
