import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { getInstallationToken } from '../github/getInstallationToken.mjs';

// Read imported repo info from last_import.json
const lastImportPath = path.join(__dirname, '..', 'ledger', 'last_import.json');
let importedRepo = null;

if (fs.existsSync(lastImportPath)) {
  importedRepo = JSON.parse(fs.readFileSync(lastImportPath, 'utf8'));
} else {
  console.error('No imported repository found. Please import a repository first.');
  process.exit(1);
}

const GITHUB_OWNER = importedRepo.owner;
const GITHUB_REPO = importedRepo.repo;
const REPO_PATH = path.join(__dirname, '..', importedRepo.path);
const GITHUB_INSTALLATION_ID = process.env.GITHUB_INSTALLATION_ID;

function logEvent(obj) {
  const eventsPath = path.join(__dirname, '..', 'ledger', 'events.log');
  fs.appendFileSync(eventsPath, JSON.stringify(obj) + '\n', 'utf8');
}

function logModelCall(obj) {
  const modelCallsPath = path.join(__dirname, '..', 'ledger', 'model_calls.log');
  fs.appendFileSync(modelCallsPath, JSON.stringify(obj) + '\n', 'utf8');
}

// Check requirements
if (!GITHUB_INSTALLATION_ID) {
  console.error('Missing required environment variable: GITHUB_INSTALLATION_ID');
  logEvent({ time: new Date().toISOString(), type: 'github_pr_failed', error: 'missing_github_installation_id' });
  process.exit(1);
}

async function createGitHubPR() {
  const originalCwd = process.cwd();

  try {
    // Get GitHub App installation token
    console.log('Getting GitHub App installation token...');
    const installationToken = await getInstallationToken(GITHUB_INSTALLATION_ID);
    logEvent({ time: new Date().toISOString(), type: 'github_token_obtained', repo: `${GITHUB_OWNER}/${GITHUB_REPO}` });

    // Change to the imported repository directory
    process.chdir(REPO_PATH);
    console.log(`Working in imported repository: ${REPO_PATH}`);

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const branchName = `sentinelchain-security-patch-${timestamp}`;

    logEvent({ time: new Date().toISOString(), type: 'github_branch_create_start', branch: branchName, repo: `${GITHUB_OWNER}/${GITHUB_REPO}` });

    // Check current branch and create new branch from it
    let baseBranch = 'main';
    try {
      const currentBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim();
      baseBranch = currentBranch;
    } catch (e) {
      // Default to main if we can't determine current branch
      baseBranch = 'main';
    }

    // Create and checkout new branch
    execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });
    logEvent({ time: new Date().toISOString(), type: 'github_branch_created', branch: branchName });

    // The patches have already been applied directly to the files by AutoFix
    // Just add and commit any changes
    execSync('git add .', { stdio: 'inherit' });

    // Check if there are changes to commit
    try {
      execSync('git diff --cached --quiet', { stdio: 'pipe' });
      console.log('No changes to commit');
      logEvent({ time: new Date().toISOString(), type: 'github_no_changes', branch: branchName });
      return { message: 'No security patches applied' };
    } catch (e) {
      // There are changes to commit
    }

    execSync(`git commit -m "🔒 Security: SentinelChain AutoFix Applied

Automated security patches applied by SentinelChain:
- Command injection protection with input sanitization
- Dangerous function usage disabled (eval, Function constructor)
- Enhanced security measures for vulnerable code patterns

Repository: ${GITHUB_OWNER}/${GITHUB_REPO}
Generated by: SentinelChain Security Analysis Platform"`, { stdio: 'inherit' });

    logEvent({ time: new Date().toISOString(), type: 'github_changes_committed', branch: branchName });

    // Ensure remote is set correctly using x-access-token format
    try {
      const remoteUrl = execSync('git remote get-url origin', { encoding: 'utf8' }).trim();
      if (!remoteUrl.includes(`${GITHUB_OWNER}/${GITHUB_REPO}`)) {
        execSync(`git remote set-url origin https://x-access-token:${installationToken}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git`, { stdio: 'inherit' });
      }
    } catch (e) {
      execSync(`git remote add origin https://x-access-token:${installationToken}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git`, { stdio: 'inherit' });
    }

    // Push branch
    execSync(`git push -u origin ${branchName}`, { stdio: 'inherit' });
    logEvent({ time: new Date().toISOString(), type: 'github_branch_pushed', branch: branchName });

    // Create PR using GitHub API
    const https = require('https');

    const prData = JSON.stringify({
      title: '🔒 Security: Command Injection Protection Patches',
      head: branchName,
      base: 'main',
      body: `## Security Patches Applied

This PR contains automated security patches generated by SentinelChain to protect against command injection vulnerabilities.

### Changes Made:
- **Input Sanitization**: Added comprehensive command validation
- **Whitelist Implementation**: Restricted allowed commands to safe operations
- **Sandbox Hardening**: Enhanced security measures in sandbox environment

### Files Modified:
- \`sandbox/app.js\` - Applied security patches

### Validation:
- All patches tested in isolated sandbox environment
- Command injection vectors blocked
- Maintains backward compatibility for safe operations

---
*Generated by SentinelChain - Automated Security Analysis Framework*`
    });

    const options = {
      hostname: 'api.github.com',
      path: `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${installationToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(prData),
        'User-Agent': 'SentinelChain-GitHub-Agent'
      }
    };

    const prPromise = new Promise((resolve, reject) => {
      const req = https.request(options, (res) => {
        let data = '';
        res.on('data', (chunk) => data += chunk);
        res.on('end', () => {
          try {
            const response = JSON.parse(data);
            if (res.statusCode >= 200 && res.statusCode < 300) {
              resolve(response);
            } else {
              reject(new Error(`GitHub API error: ${res.statusCode} - ${response.message || data}`));
            }
          } catch (e) {
            reject(e);
          }
        });
      });

      req.on('error', reject);
      req.write(prData);
      req.end();
    });

    const prResponse = await prPromise;
    const prUrl = prResponse.html_url;

    logEvent({
      time: new Date().toISOString(),
      type: 'github_pr_created',
      branch: branchName,
      pr_url: prUrl,
      pr_number: prResponse.number
    });

    logModelCall({
      timestamp: new Date().toISOString(),
      agent: 'prepare_pr_github',
      action: 'pr_created',
      branch: branchName,
      pr_url: prUrl,
      success: true
    });

    console.log(`✅ GitHub PR created successfully!`);
    console.log(`🔗 PR URL: ${prUrl}`);
    console.log(`🌿 Branch: ${branchName}`);

    // Switch back to main branch
    execSync('git checkout main', { stdio: 'inherit' });

    return { prUrl, branchName };

  } catch (error) {
    console.error('❌ GitHub PR creation failed:', error.message);

    logModelCall({
      timestamp: new Date().toISOString(),
      agent: 'prepare_pr_github',
      error: error.message,
      success: false
    });

    logEvent({
      time: new Date().toISOString(),
      type: 'github_pr_failed',
      error: error.message
    });

    // Try to switch back to main branch
    try {
      execSync('git checkout main', { stdio: 'inherit' });
    } catch (e) {
      console.error('Could not switch back to main branch:', e.message);
    }

    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  createGitHubPR().catch(console.error);
}

module.exports = { createGitHubPR };
