const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

function logEvent(obj) {
  const eventsPath = path.join(__dirname, '..', 'ledger', 'events.log');
  fs.appendFileSync(eventsPath, JSON.stringify(obj) + '\n', 'utf8');
}

function logModelCall(obj) {
  const modelCallsPath = path.join(__dirname, '..', 'ledger', 'model_calls.log');
  fs.appendFileSync(modelCallsPath, JSON.stringify(obj) + '\n', 'utf8');
}

// Check environment variables
if (!GITHUB_OWNER || !GITHUB_REPO || !GITHUB_TOKEN) {
  console.error('Missing required environment variables: GITHUB_OWNER, GITHUB_REPO, GITHUB_TOKEN');
  logEvent({ time: new Date().toISOString(), type: 'github_pr_failed', error: 'missing_env_vars' });
  process.exit(1);
}

async function createGitHubPR() {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const branchName = `sentinelchain-security-patch-${timestamp}`;

    logEvent({ time: new Date().toISOString(), type: 'github_branch_create_start', branch: branchName });

    // Create and checkout new branch
    execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });
    logEvent({ time: new Date().toISOString(), type: 'github_branch_created', branch: branchName });

    // Copy patched file to original location for commit
    const patchedPath = path.join(__dirname, '..', 'sandbox', 'app.patched.js');
    const originalPath = path.join(__dirname, '..', 'sandbox', 'app.js');

    if (fs.existsSync(patchedPath)) {
      fs.copyFileSync(patchedPath, originalPath);
      logEvent({ time: new Date().toISOString(), type: 'patched_file_applied', from: patchedPath, to: originalPath });
    }

    // Add and commit changes
    execSync('git add .', { stdio: 'inherit' });
    execSync(`git commit -m "Security: Apply command injection protection patches

- Added input sanitization to prevent command injection
- Implemented whitelist-based command validation
- Enhanced sandbox security measures

Generated by SentinelChain security analysis."`, { stdio: 'inherit' });

    logEvent({ time: new Date().toISOString(), type: 'github_changes_committed', branch: branchName });

    // Set remote if not exists
    try {
      execSync('git remote get-url origin', { stdio: 'pipe' });
    } catch (e) {
      execSync(`git remote add origin https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git`, { stdio: 'inherit' });
    }

    // Push branch
    execSync(`git push -u origin ${branchName}`, { stdio: 'inherit' });
    logEvent({ time: new Date().toISOString(), type: 'github_branch_pushed', branch: branchName });

    // Create PR using GitHub API
    const https = require('https');

    const prData = JSON.stringify({
      title: '🔒 Security: Command Injection Protection Patches',
      head: branchName,
      base: 'main',
      body: `## Security Patches Applied

This PR contains automated security patches generated by SentinelChain to protect against command injection vulnerabilities.

### Changes Made:
- **Input Sanitization**: Added comprehensive command validation
- **Whitelist Implementation**: Restricted allowed commands to safe operations
- **Sandbox Hardening**: Enhanced security measures in sandbox environment

### Files Modified:
- \`sandbox/app.js\` - Applied security patches

### Validation:
- All patches tested in isolated sandbox environment
- Command injection vectors blocked
- Maintains backward compatibility for safe operations

---
*Generated by SentinelChain - Automated Security Analysis Framework*`
    });

    const options = {
      hostname: 'api.github.com',
      path: `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls`,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(prData),
        'User-Agent': 'SentinelChain-GitHub-Agent'
      }
    };

    const prPromise = new Promise((resolve, reject) => {
      const req = https.request(options, (res) => {
        let data = '';
        res.on('data', (chunk) => data += chunk);
        res.on('end', () => {
          try {
            const response = JSON.parse(data);
            if (res.statusCode >= 200 && res.statusCode < 300) {
              resolve(response);
            } else {
              reject(new Error(`GitHub API error: ${res.statusCode} - ${response.message || data}`));
            }
          } catch (e) {
            reject(e);
          }
        });
      });

      req.on('error', reject);
      req.write(prData);
      req.end();
    });

    const prResponse = await prPromise;
    const prUrl = prResponse.html_url;

    logEvent({
      time: new Date().toISOString(),
      type: 'github_pr_created',
      branch: branchName,
      pr_url: prUrl,
      pr_number: prResponse.number
    });

    logModelCall({
      timestamp: new Date().toISOString(),
      agent: 'prepare_pr_github',
      action: 'pr_created',
      branch: branchName,
      pr_url: prUrl,
      success: true
    });

    console.log(`✅ GitHub PR created successfully!`);
    console.log(`🔗 PR URL: ${prUrl}`);
    console.log(`🌿 Branch: ${branchName}`);

    // Switch back to main branch
    execSync('git checkout main', { stdio: 'inherit' });

    return { prUrl, branchName };

  } catch (error) {
    console.error('❌ GitHub PR creation failed:', error.message);

    logModelCall({
      timestamp: new Date().toISOString(),
      agent: 'prepare_pr_github',
      error: error.message,
      success: false
    });

    logEvent({
      time: new Date().toISOString(),
      type: 'github_pr_failed',
      error: error.message
    });

    // Try to switch back to main branch
    try {
      execSync('git checkout main', { stdio: 'inherit' });
    } catch (e) {
      console.error('Could not switch back to main branch:', e.message);
    }

    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  createGitHubPR().catch(console.error);
}

module.exports = { createGitHubPR };
